name: task_manager
description: " A small Task Manager Flutter app with BLoC and clean architecture."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  pedantic: ^1.11.1


flutter:

  uses-material-design: true

  assets:
    - screenshots/task2.png
    - screenshots/task3.png
    - screenshots/task4.png
